{%- set esng = salt['pillar.get']('elasticsearch-ng', {}) %}
filebeat:
  config_dir: 'd:\apps\filebeat\conf.d'

output.elasticsearch:
  hosts: ['{{ esng.hosts }}']
  username: '{{ esng.username }}'
  password: '{{ esng.password }}'
  index: '%{[fields.index]}'

processors:
- drop_fields:
    fields: ['offset', 'beat.name', 'beat.version']
- drop_event:
    when:
      regexp:
        message: '^#'
- drop_event:
    when:
      contains:
        message: 'ELB-HealthChecker/2.0'

logging.to_files: true
logging.files:
  path: 'd:\data\logs\filebeat'
  name: 'filebeat.log'
